### ISSUE TITLE
Default expiration not working

### ISSUE THREAD

**Issue by roasted-watermelon** [rhee876527/chiyogami#6]
Here is the compose file I am using, I want to set the expiration to "Never" by default.

```
services:
  chiyogami:
    image: ghcr.io/rhee876527/chiyogami:${VERSION}
    container_name: chiyogami
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - CHOWN
    security_opt:
      - no-new-privileges
    volumes:
      - ./pastes:/pastes
    environment:
      #  Keep this secure and unique.
      #  Example to generate random string: `openssl rand -base64 32`
      - SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      # Run application as preferred user
      # By default runs as user 1000:1000
      #- GID=1000
      #- UID=1000
      - PASTE_DEFAULT_EXPIRATION=Never
    ports:
      - 2246:8000
    restart: unless-stopped
```
The `VERSION` is from a `.env` file currently set to "1.3.8"

Even after recreating the container i.e. `docker compose up -d --force-recreate` the expiration is still set to "1 day" by default. Tried it on private tab as well.
